//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Prueba_Tecnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public int ID_CONTACTO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public Nullable<int> ID_TIPO_CONTACTO { get; set; }
        public string VALOR_CONTACTO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual TIPO_CONTACTO TIPO_CONTACTO { get; set; }
    }
}
