//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Prueba_Tecnica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NOTA_CREDITO_DEBITO
    {
        public int ID_NOTA_CREDITO_DEBITO { get; set; }
        public Nullable<int> ID_CUENTA { get; set; }
        public Nullable<int> ES_NOTA_CREDITO { get; set; }
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public Nullable<long> VALOR_NOTA_CREDITO_DEBITO { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
        public virtual TIPO_CONDICION TIPO_CONDICION { get; set; }
    }
}
