//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Prueba_Tecnica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRUEBA_TECNICAEntities2 : DbContext
    {
        public PRUEBA_TECNICAEntities2()
            : base("name=PRUEBA_TECNICAEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<CONTACTO> CONTACTO { get; set; }
        public virtual DbSet<CUENTA> CUENTA { get; set; }
        public virtual DbSet<NOTA_CREDITO_DEBITO> NOTA_CREDITO_DEBITO { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_CONDICION> TIPO_CONDICION { get; set; }
        public virtual DbSet<TIPO_CONTACTO> TIPO_CONTACTO { get; set; }
        public virtual DbSet<TIPO_CUENTA> TIPO_CUENTA { get; set; }
        public virtual DbSet<TIPO_DOCUMENTO> TIPO_DOCUMENTO { get; set; }
        public virtual DbSet<TIPO_ESTADO> TIPO_ESTADO { get; set; }
    }
}
