//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_Prueba_Tecnica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CONDICION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_CONDICION()
        {
            this.NOTA_CREDITO_DEBITO = new HashSet<NOTA_CREDITO_DEBITO>();
        }
    
        public int ID_TIPO_CONDICION { get; set; }
        public string DESCRIPCION_TIPO_CONDICION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTA_CREDITO_DEBITO> NOTA_CREDITO_DEBITO { get; set; }
    }
}
